#!/bin/bash


# make sure user is root
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root." 
	exit 1
fi

echo ''
echo "Make sure you have reviewed the varibles in ansible/vars."
echo "If not, exit this script and do so now, no changes were"
echo "made."
echo ''

# login info for ansible
read -p "Ssh username (needs sudo power): " ssh_username
read -s -p "Ssh password: " ssh_password

echo ''


# skip installing ansible if already installed
if ! command -v ansible > /dev/null 2>&1; then

		dnf update
		dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
		dnf -y install --enablerepo epel-playground ansible

else

	echo ''
	echo ''
	echo "Ansible is installed. Skipping ansible Installation."

fi

cd ansible

ansible-playbook install.yml -e "ansible_user=${ssh_username} ansible_ssh_pass=${ssh_password} ansible_sudo_pass=${ssh_password}"
